# Generated by Django 4.2.1 on 2023-05-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0002_remove_recipe_easy_to_make"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="rating",
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
